---
# This playbook performs a DC/OS upgrade

- name: added localhost to in-memory inventory
  hosts: all
  gather_facts: no
  tasks:
    - add_host:
        hostname: localhost
        ansible_connection: local
        ansible_host: 127.0.0.1

- name: setup the system requirements on all nodes
  hosts: all:!localhost
  serial: 20
  become: true
  roles:
    - common
    - docker

- name: generate upgrade configuration
  hosts: bootstraps
  serial: 1
  become: true
  vars:
    dcos_upgrade: true
  roles:
    - bootstrap

- name: upgrade masters
  hosts: masters
  serial: 1
  become: true
  roles:
    - node-upgrade

- name: upgrade agents
  hosts: [ agents, agent_publics]
  serial: 20
  become: true
  roles:
    - node-upgrade

- name: upgrade CLIs on control machine
  hosts: localhost
  serial: 1
  environment:
    PATH: '..:{{ ansible_env.PATH }}'
  roles:
    - { role: cli, cli_upgrade: true }
